import type { Metadata } from 'next';
import { FileText } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Use — CLARITY Health',
  description:
    'Terms of use for CLARITY Health. CLARITY is an educational tool and does not provide medical advice, diagnosis, or treatment.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen">
      {/* Hero */}
      <section className="bg-gradient-to-b from-white to-blue-50 pb-16 pt-16 sm:pt-24">
        <div className="mx-auto max-w-4xl px-4 text-center sm:px-6 lg:px-8">
          <div className="mx-auto mb-6 flex h-16 w-16 items-center justify-center rounded-full bg-blue-100">
            <FileText className="h-8 w-8 text-[#3B82F6]" />
          </div>
          <h1 className="font-serif text-4xl font-bold tracking-tight text-slate-900 md:text-5xl">
            Terms of Use
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-slate-600">
            Please read these terms carefully before using CLARITY. We have written
            them in plain language because we believe legal documents should be
            understandable too.
          </p>
        </div>
      </section>

      {/* Terms Content */}
      <section className="bg-white py-20 px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl space-y-12">
          {/* Educational Nature */}
          <div>
            <h2 className="font-serif text-2xl font-bold text-slate-900">
              1. Educational Purpose Only
            </h2>
            <div className="mt-5 rounded-2xl bg-amber-50 border border-amber-100 p-6">
              <p className="font-semibold text-amber-800">
                This is the most important section of these terms.
              </p>
              <p className="mt-3 text-amber-700 leading-relaxed">
                CLARITY is an educational tool. It does not provide medical advice,
                medical opinions, diagnoses, or treatment recommendations. The
                information generated by CLARITY is for general educational purposes
                only and should never be used as a substitute for professional medical
                advice.
              </p>
            </div>
            <p className="mt-5 text-slate-600 leading-relaxed">
              CLARITY uses artificial intelligence to translate medical concepts into
              plain language. While we strive for accuracy, the information provided
              may not be complete, may not apply to your specific situation, and may
              not reflect the most recent medical developments.
            </p>
            <p className="mt-3 text-slate-600 leading-relaxed">
              You should always consult with a qualified healthcare professional
              for medical advice tailored to your individual circumstances.
            </p>
          </div>

          {/* Not a Substitute */}
          <div>
            <h2 className="font-serif text-2xl font-bold text-slate-900">
              2. Not a Substitute for Professional Medical Care
            </h2>
            <p className="mt-5 text-slate-600 leading-relaxed">
              CLARITY is designed to help you understand medical information and
              prepare for conversations with your healthcare team. It is not designed
              to replace those conversations.
            </p>
            <ul className="mt-4 space-y-3 text-slate-600">
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                Never delay seeking medical attention because of information from CLARITY
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                Never disregard professional medical advice because of something CLARITY generated
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                Never use CLARITY to self-diagnose or self-treat any condition
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                If you are experiencing a medical emergency, call 911 or your local emergency number immediately
              </li>
            </ul>
          </div>

          {/* Use at Your Own Discretion */}
          <div>
            <h2 className="font-serif text-2xl font-bold text-slate-900">
              3. Use at Your Own Discretion
            </h2>
            <p className="mt-5 text-slate-600 leading-relaxed">
              You are free to use CLARITY as an educational resource. However, any
              decisions you make regarding your health based on information from
              CLARITY are your own responsibility. We encourage you to use CLARITY
              reports as a conversation starter with your doctor, not as a
              definitive source of medical truth.
            </p>
            <p className="mt-3 text-slate-600 leading-relaxed">
              By using CLARITY, you acknowledge that you understand the educational
              nature of this tool and accept full responsibility for how you use the
              information it provides.
            </p>
          </div>

          {/* Content Accuracy */}
          <div>
            <h2 className="font-serif text-2xl font-bold text-slate-900">
              4. Content Accuracy
            </h2>
            <p className="mt-5 text-slate-600 leading-relaxed">
              CLARITY uses AI technology to generate educational health content. While
              we work to provide accurate and up-to-date information:
            </p>
            <ul className="mt-4 space-y-3 text-slate-600">
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                AI-generated content may occasionally contain errors or omissions
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                Medical knowledge evolves rapidly and information may become outdated
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                Individual medical situations are unique and general information may not apply to your case
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                Treatment options and guidelines vary by location and healthcare system
              </li>
            </ul>
            <p className="mt-4 text-slate-600 leading-relaxed">
              We do not guarantee the accuracy, completeness, or timeliness of any
              information provided by CLARITY. Always verify important health
              information with your healthcare provider.
            </p>
          </div>

          {/* Limitation of Liability */}
          <div>
            <h2 className="font-serif text-2xl font-bold text-slate-900">
              5. Limitation of Liability
            </h2>
            <p className="mt-5 text-slate-600 leading-relaxed">
              To the fullest extent permitted by law, CLARITY Health, Vilmure
              Ventures, and their officers, directors, employees, and agents shall
              not be liable for any direct, indirect, incidental, consequential, or
              punitive damages arising from:
            </p>
            <ul className="mt-4 space-y-3 text-slate-600">
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                Your use of or reliance on information provided by CLARITY
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                Any errors or omissions in the content generated
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                Any health decisions made based on CLARITY reports
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                Service interruptions or technical issues
              </li>
            </ul>
            <p className="mt-4 text-slate-600 leading-relaxed">
              CLARITY is provided &quot;as is&quot; and &quot;as available&quot; without
              warranties of any kind, either express or implied, including but not
              limited to implied warranties of merchantability, fitness for a
              particular purpose, or non-infringement.
            </p>
          </div>

          {/* Intellectual Property */}
          <div>
            <h2 className="font-serif text-2xl font-bold text-slate-900">
              6. Intellectual Property
            </h2>
            <p className="mt-5 text-slate-600 leading-relaxed">
              The CLARITY name, logo, design, and underlying technology are the
              property of Vilmure Ventures. You may not copy, modify, distribute, or
              create derivative works from CLARITY without our prior written consent.
            </p>
            <p className="mt-3 text-slate-600 leading-relaxed">
              Reports generated by CLARITY for your personal use are yours to keep,
              print, share with your healthcare team, or save. We do not claim
              ownership of the personalized reports generated for you.
            </p>
          </div>

          {/* Acceptable Use */}
          <div>
            <h2 className="font-serif text-2xl font-bold text-slate-900">
              7. Acceptable Use
            </h2>
            <p className="mt-5 text-slate-600 leading-relaxed">
              You agree to use CLARITY only for its intended purpose: personal health
              education. You may not:
            </p>
            <ul className="mt-4 space-y-3 text-slate-600">
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                Use CLARITY to provide medical advice to others
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                Represent CLARITY output as professional medical guidance
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                Attempt to reverse-engineer, disassemble, or extract the underlying AI models
              </li>
              <li className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-slate-400" />
                Use automated systems to access CLARITY in a manner that exceeds reasonable use
              </li>
            </ul>
          </div>

          {/* Changes to Terms */}
          <div>
            <h2 className="font-serif text-2xl font-bold text-slate-900">
              8. Changes to These Terms
            </h2>
            <p className="mt-5 text-slate-600 leading-relaxed">
              We may update these terms from time to time. When we make significant
              changes, we will update the date at the bottom of this page. Your
              continued use of CLARITY after changes are posted constitutes your
              acceptance of the revised terms.
            </p>
          </div>

          {/* Governing Law */}
          <div>
            <h2 className="font-serif text-2xl font-bold text-slate-900">
              9. Governing Law
            </h2>
            <p className="mt-5 text-slate-600 leading-relaxed">
              These terms shall be governed by and construed in accordance with the
              laws of the United States. Any disputes arising from these terms or
              your use of CLARITY shall be resolved in accordance with applicable law.
            </p>
          </div>

          {/* Contact */}
          <div>
            <h2 className="font-serif text-2xl font-bold text-slate-900">
              10. Contact Us
            </h2>
            <p className="mt-5 text-slate-600 leading-relaxed">
              If you have any questions about these terms, please contact us:
            </p>
            <div className="mt-4 rounded-xl bg-blue-50 border border-blue-100 p-5">
              <p className="font-medium text-slate-900">CLARITY Health</p>
              <p className="text-slate-600">A Vilmure Ventures Company</p>
              <p className="mt-2 text-[#3B82F6]">hello@clarityhealth.ai</p>
            </div>
          </div>

          {/* Last Updated */}
          <div className="border-t border-slate-200 pt-8">
            <p className="text-sm text-slate-400">
              Last updated: March 2026
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
